security:
    encoders:
        AppBundle\Entity\Ln2user: bcrypt
    providers:
        database_users:
            entity: { class: AppBundle:Ln2user, property: usernam }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /