<?php

namespace AppBundle\Repository;

/**
 * Ln2userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ln2userRepository extends \Doctrine\ORM\EntityRepository
{
}
